export const basicPrettierConflicts = [
  '@typescript-eslint/brace-style',
  '@typescript-eslint/func-call-spacing',
  '@typescript-eslint/indent',
  '@typescript-eslint/semi',
  'array-bracket-spacing',
  'arrow-parens',
  'arrow-spacing',
  'block-spacing',
  'comma-dangle',
  'comma-spacing',
  'comma-style',
  'computed-property-spacing',
  'dot-location',
  'eol-last',
  'function-paren-newline',
  'generator-star-spacing',
  'implicit-arrow-linebreak',
  'key-spacing',
  'keyword-spacing',
  'linebreak-style',
  'new-parens',
  'newline-per-chained-call',
  'no-extra-semi',
  'no-floating-decimal',
  'no-mixed-spaces-and-tabs',
  'no-multi-spaces',
  'no-multiple-empty-lines',
  'no-spaced-func',
  'no-trailing-spaces',
  'no-whitespace-before-property',
  'nonblock-statement-body-position',
  'object-curly-newline',
  'object-curly-spacing',
  'object-property-newline',
  'one-var-declaration-per-line',
  'operator-linebreak',
  'padded-blocks',
  'quote-props',
  'rest-spread-spacing',
  'semi-spacing',
  'semi-style',
  'space-before-blocks',
  'space-before-function-paren',
  'space-in-parens',
  'space-infix-ops',
  'space-unary-ops',
  'switch-colon-spacing',
  'template-curly-spacing',
  'template-tag-spacing',
  'unicode-bom',
  'wrap-iife',
  'yield-star-spacing'
];

export const additional = ['no-console'];

// TODO
export const conflictingOptions = ['curly', 'no-confusing-arrow'];

// TODO
export const cantBeChecked = [
  '@typescript-eslint/quotes',
  'arrow-body-style',
  'max-len',
  'no-mixed-operators',
  'no-tabs',
  'no-unexpected-multiline',
  'prefer-arrow-callback'
];
